### ISSUE TITLE
gt4py imports not working

### ISSUE THREAD

**Issue by nbren12** [ai2cm/packages#51]
To reproduce, make use this `shell.nix`:
```
# shell.nix
let
  pkgs = import (builtins.fetchGit {
    # Descriptive name to make the store path easier to identify
    name = "ai2cm-packages";
    url = "git@github.com:VulcanClimateModeling/packages.git";
    ref = "master";
    # SHA of the commit of pkgs to use. This effectively pins all packages to
    # the versions specified in that commit.
    rev = "b3194fd82e98c288d04ca6fdd1091b484371b26c";
    # rev = "7f6bd8ccb8217fc6012aa287d8e61474ee4d46e3";
  }) { };
in pkgs.mkShell {
    buildInputs = [ pkgs.serialbox pkgs.python38Packages.gt4py-dev];
    serialbox = pkgs.serialbox;
    shellHook =''
      export PYTHONPATH=$serialbox/python:$PYTHONPATH
    '';
}
```
and run `nix-shell —run “python -c ‘import gt4py’”. 

Here is the full error message:
```
$ python3 -c 'import gt4py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/b1c4ycdmw2pclpmvi5yx8aaj14dshj56-python3.8-gt4py-0.1.0-dev/lib/python3.8/site-packages/gt4py/__init__.py", line 45, in <module>
    from . import gtscript
  File "/nix/store/b1c4ycdmw2pclpmvi5yx8aaj14dshj56-python3.8-gt4py-0.1.0-dev/lib/python3.8/site-packages/gt4py/gtscript.py", line 34, in <module>
    from gt4py.stencil_builder import StencilBuilder
  File "/nix/store/b1c4ycdmw2pclpmvi5yx8aaj14dshj56-python3.8-gt4py-0.1.0-dev/lib/python3.8/site-packages/gt4py/stencil_builder.py", line 6, in <module>
    from gt4py.backend.gtc_backend.defir_to_gtir import DefIRToGTIR
  File "/nix/store/b1c4ycdmw2pclpmvi5yx8aaj14dshj56-python3.8-gt4py-0.1.0-dev/lib/python3.8/site-packages/gt4py/backend/__init__.py", line 27, in <module>
    from .gtc_backend import *
  File "/nix/store/b1c4ycdmw2pclpmvi5yx8aaj14dshj56-python3.8-gt4py-0.1.0-dev/lib/python3.8/site-packages/gt4py/backend/gtc_backend/__init__.py", line 17, in <module>
    from .cuda.backend import GTCCudaBackend
  File "/nix/store/b1c4ycdmw2pclpmvi5yx8aaj14dshj56-python3.8-gt4py-0.1.0-dev/lib/python3.8/site-packages/gt4py/backend/gtc_backend/cuda/backend.py", line 37, in <module>
    from gtc.passes.oir_pipeline import OirPipeline
  File "/nix/store/b1c4ycdmw2pclpmvi5yx8aaj14dshj56-python3.8-gt4py-0.1.0-dev/lib/python3.8/site-packages/gtc/passes/oir_pipeline.py", line 21, in <module>
    from gtc.passes.oir_dace_optimizations.horizontal_execution_merging import (
  File "/nix/store/b1c4ycdmw2pclpmvi5yx8aaj14dshj56-python3.8-gt4py-0.1.0-dev/lib/python3.8/site-packages/gtc/passes/oir_dace_optimizations/__init__.py", line 17, in <module>
    from .api import optimize_horizontal_executions
  File "/nix/store/b1c4ycdmw2pclpmvi5yx8aaj14dshj56-python3.8-gt4py-0.1.0-dev/lib/python3.8/site-packages/gtc/passes/oir_dace_optimizations/api.py", line 17, in <module>
    from dace.transformation.transformation import Transformation
ImportError: cannot import name 'Transformation' from 'dace.transformation.transformation' (/nix/store/1i9v1pdps60vy4lwm7xvdx2rkd018hjl-python3.8-dace-0.13/lib/python3.8/site-packages/dace/transformation/transformation.py)
```

**Comment by nbren12** [comment]
Note that this import works when using 7f6bd8ccb8217fc6012aa287d8e61474ee4d46e3.
